app/home/forms.py
# app/home/forms.py

from flask_wtf import FlaskForm
from wtforms.fields.html5 import DateField
from wtforms import StringField, SubmitField, ValidationError, SelectField, FloatField
from wtforms.validators import DataRequired, Email
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from ..models import Product, Supplier, Shipment


class ProductForm(FlaskForm):
    """
    Form to add or edit a Product
    """
    name = StringField('Name', validators=[DataRequired()])
    mfg_date = DateField('Mfg. Date', validators=[DataRequired()])
    rcv_date = DateField('Rcv. Date', validators=[DataRequired()])
    exp_date = DateField('Exp. Date', validators=[DataRequired()])
    location = StringField('Location', validators=[DataRequired()])
    stock = FloatField('Stock', validators=[DataRequired()])
    supplier = QuerySelectField('Supplier', validators=[DataRequired()],
                                query_factory=lambda: Supplier.query.all(),
                                get_label="name")

    submit = SubmitField('Submit')


class SupplierForm(FlaskForm):
    """
    Form to add or edit a Supplier
    """
    name = StringField('Name', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    contact = StringField('Contact', validators=[DataRequired()])
    address = StringField('Address', validators=[DataRequired()])
    submit = SubmitField('Submit')


class ShipmentForm(FlaskForm):
    """
    Form to add or edit a Supplier
    """
    product = QuerySelectField('Product', validators=[DataRequired()],
                               query_factory=lambda: Product.query.all(),
                               get_label="name")
    department = SelectField('Department', validators=[DataRequired()], choices=[('Quality', 'Quality'),
                                                                                 ('Production', 'Production'),
                                                                                 ('Other', 'Other')])
    name = StringField('Name', validators=[DataRequired()])
    quantity = FloatField('Quantity', validators=[DataRequired()])
    shipment_date = DateField('Shipment Date', validators=[DataRequired()])
    submit = SubmitField('Submit')

app/home/__init__.py
# app/home/__init__.py

from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

app/home/views.py
# app/home/views.py

from flask_login import login_required, current_user
from flask import abort, flash, redirect, render_template, url_for, request
from sqlalchemy import func, case, literal_column, select
from sqlalchemy.sql import label
import pandas as pd

from app.home.forms import ProductForm, SupplierForm, ShipmentForm
from . import home
from ..models import Product, Supplier, Shipment, Transaction
from .. import db


@home.route('/')
def index():
    """
    Render the home template on the / route
    """
    return render_template('home/index.html', title="P3I")


@home.route('/products')
@login_required
def list_products():
    """
    Render the home template on the / route
    """
    products = Product.query.all()
    return render_template('home/products/list.html', products=products, title="Products")


@home.route('/products/add', methods=['GET', 'POST'])
@login_required
def add_product():
    """
    Add a product to the database
    """

    _add_product = True

    form = ProductForm()
    if form.validate_on_submit():
        product = Product(name=form.name.data,
                          mfg_date=form.mfg_date.data,
                          exp_date=form.exp_date.data,
                          rcv_date=form.rcv_date.data,
                          location=form.location.data,
                          stock=form.stock.data,
                          supplier=form.supplier.data)
        try:
            # add product and a transaction to the database
            if product.stock <= 0:
                flash('Invalid stock entry, please enter a positive number!')
            else:
                transaction = Transaction(
                    product=product,
                    date=product.rcv_date,
                    quantity=product.stock
                )
                db.session.add(product)
                db.session.add(transaction)
                db.session.commit()
                flash('You have successfully added a new product.')
        except:
            flash('Error: An error occurred.')

        # redirect to departments page
        return redirect(url_for('home.list_products'))
    # Redirect to add supplier as we need it to add a product
    elif Supplier.query.count() == 0:
        return redirect(url_for('home.add_supplier'))

    # load product template
    return render_template('home/products/add.html', action="Add",
                           add_product=_add_product, form=form,
                           title="Add Product")


@home.route('/products/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_product(id):
    """
    Edit a product
    """
    _add_product = False

    product = Product.query.get_or_404(id)
    form = ProductForm(obj=product)
    if form.validate_on_submit():
        product.name = form.name.data
        product.mfg_date = form.mfg_date.data
        product.exp_date = form.exp_date.data
        product.rcv_date = form.rcv_date.data
        product.location = form.location.data
        product.stock = form.stock.data
        product.supplier = form.supplier.data
        db.session.commit()
        flash('You have successfully edited the product.')

        # redirect to the departments page
        return redirect(url_for('home.list_products'))

    form.name.data = product.name
    form.mfg_date.data = product.mfg_date
    form.exp_date.data = product.exp_date
    form.rcv_date.data = product.rcv_date
    form.stock.data = product.stock
    form.supplier.data = product.supplier

    return render_template('home/products/add.html', action="Edit",
                           add_product=_add_product, form=form,
                           product=product, title="Edit Product")


@home.route('/products/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_product(id):
    """
    Delete a product from the database
    """
    if not current_user.is_admin:
        abort(403)
    product = Product.query.get_or_404(id)
    db.session.delete(product)
    db.session.commit()
    flash('You have successfully deleted the product.')

    # redirect to the departments page
    return redirect(url_for('home.list_products'))


@home.route('/suppliers')
@login_required
def list_suppliers():
    """
    Render the home template on the /suppliers route
    """
    suppliers = Supplier.query.all()
    return render_template('home/suppliers/list.html', suppliers=suppliers, title="Suppliers")


@home.route('/suppliers/add', methods=['GET', 'POST'])
@login_required
def add_supplier():
    """
    Add a supplier to the database
    """

    _add_supplier = True

    form = SupplierForm()
    if form.validate_on_submit():
        supplier = Supplier(name=form.name.data,
                            email=form.email.data,
                            contact=form.contact.data,
                            address=form.address.data)
        try:
            # add supplier to the database
            db.session.add(supplier)
            db.session.commit()
            flash('You have successfully added a new supplier.')
        except:
            # in case supplier email already exists
            flash('Error: An error occurred.')

        # redirect to departments page
        return redirect(url_for('home.list_suppliers'))

    # load supplier template
    return render_template('home/suppliers/add.html', action="Add",
                           add_supplier=_add_supplier, form=form,
                           title="Add Supplier")


@home.route('/suppliers/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_supplier(id):
    """
    Edit a supplier
    """
    _add_supplier = False

    supplier = Supplier.query.get_or_404(id)
    form = SupplierForm(obj=supplier)
    if form.validate_on_submit():
        supplier.name = form.name.data
        supplier.email = form.email.data
        supplier.contact = form.contact.data
        supplier.address = form.address.data
        db.session.commit()
        flash('You have successfully edited the supplier.')

        # redirect to the departments page
        return redirect(url_for('home.list_suppliers'))
    else:
        form.name.data = supplier.name
        form.email.data = supplier.email
        form.contact.data = supplier.contact
        form.address.data = supplier.address
        return render_template('home/suppliers/add.html', action="Edit",
                               add_supplier=_add_supplier, form=form,
                               supplier=supplier, title="Edit Supplier")


@home.route('/suppliers/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_supplier(id):
    """
    Delete a supplier from the database
    """
    if not current_user.is_admin:
        abort(403)
    supplier = Supplier.query.get_or_404(id)
    db.session.delete(supplier)
    db.session.commit()
    flash('You have successfully deleted the supplier.')

    # redirect to the departments page
    return redirect(url_for('home.list_suppliers'))


@home.route('/shipments')
@login_required
def list_shipments():
    """
    Render the home template on the /shipments route
    """
    shipments = Shipment.query.all()
    return render_template('home/shipments/list.html', shipments=shipments, title="Shipments")


@home.route('/shipments/add', methods=['GET', 'POST'])
@login_required
def add_shipment():
    """
    Add a shipment to the database
    """

    _add_shipment = True

    form = ShipmentForm()
    if form.validate_on_submit():
        shipment = Shipment(department=form.department.data,
                            name=form.name.data,
                            quantity=form.quantity.data,
                            shipment_date=form.shipment_date.data,
                            product=form.product.data)
        try:
            # add shipment to the database and update product
            product = Product.query.get_or_404(form.product.data.id)
            product.stock -= shipment.quantity
            transaction = Transaction(
                product=product,
                date=product.rcv_date,
                quantity=-shipment.quantity
            )
            if product.stock < 0 or shipment.quantity <= 0:
                flash('Specified quantity is not correct or not available')
            else:
                db.session.add(shipment)
                db.session.add(transaction)
                db.session.commit()
                flash('You have successfully added a new shipment.')
        except:
            # in case shipment already exists
            flash('Error: An error occurred.')

        # redirect to departments page
        return redirect(url_for('home.list_shipments'))

    # load shipment template
    return render_template('home/shipments/add.html', action="Add",
                           add_shipment=_add_shipment, form=form,
                           title="Add Shipment")


@home.route('/shipments/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_shipment(id):
    """
    Edit a shipment
    """
    _add_shipment = False

    shipment = Shipment.query.get_or_404(id)
    form = ShipmentForm(obj=shipment)
    if form.validate_on_submit():
        old_prod = Product.query.get_or_404(shipment.product.id)
        old_prod.stock += shipment.quantity
        shipment.department = form.department.data
        shipment.name = form.name.data
        shipment.quantity = form.quantity.data
        shipment.shipment_date = form.shipment_date.data
        shipment.product = form.product.data
        new_prod = Product.query.get_or_404(shipment.product.id)
        new_prod.stock -= shipment.quantity
        if new_prod.stock < 0:
            flash('Specified quantity is not available')
        else:
            db.session.commit()
            flash('You have successfully edited the shipment.')

        # redirect to the departments page
        return redirect(url_for('home.list_shipments'))
    else:

app/templates/home/products/add.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block body %}
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        {% if add_product %}
        Add Product
        {% else %}
        Edit Product
        {% endif %}
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Products</a></li>
        <li class="active">
            {% if add_product %}
            Add Product
            {% else %}
            Edit Product
            {% endif %}
        </li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title col-md-10">Product</h3>
                    <div>
                    </div>
                </div>
                <div class="box-body">
                    {{ wtf.quick_form(form) }}
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

app/templates/home/products/list.html
<!-- app/templates/home/index.html -->

{% extends "base.html" %}
{% block body %}
<b>
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Products
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Products</li>
        </ol>
    </section>
    <!-- Main content -->
</b>
<section class="content">
    <b></b>
    <div class="row">
        <b></b>
        <div class="col-xs-12">
            <b></b>
            <div class="box">
                <b>
                    <div class="box-header">
                        <div>
                            <a style="float:right" href="{{ url_for('home.add_product') }}">
                                <button class="btn btn-primary">
                                    <i class="fa fa-plus"></i>
                                    Add Product
                                </button>
                            </a>
                        </div>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Location</th>
                                <th>Quantity</th>
                                <th>Received On</th>
                                <th>Expiry</th>
                                <th>Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for p in products%}
                            <tr>
                                <td> {{ p.id }}</td>
                                <td> {{ p.name }}</td>
                                <td> {{ p.location }}</td>
                                <td> {{ p.stock }}</td>
                                <td> {{ p.rcv_date }}</td>
                                <td> {{ p.exp_date }}</td>
                                <td class="dontprint">
                                    <a type="button" class="btn btn-info"
                                       href="{{ url_for('home.edit_product', id=p.id) }}">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                    <button type="button" class="btn btn-primary" onclick="pShipment(this)"><i
                                            class="fa fa-print"></i></button>
                                    {% if current_user.is_admin %}
                                <a type="button" class="btn btn-danger"
                                       href="{{ url_for('home.delete_product', id=p.id) }}">
                                        <i class="fa fa-trash"></i>
                                    </a>
                                {% endif %}

                                </td>
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </b>
                <b>
                    <!-- /.box-body -->
                </b>
            </div>
            <b>
                <!-- /.box -->
            </b>
        </div>
        <b>
            <!-- /.col -->
        </b>
    </div>
    <b>
        <!-- /.row -->
    </b>
</section>
<!-- print div -->
<div id="print" class="content print" style="display:none;">
    <div style="font-size:28px">
        <img src="{{ url_for('static', filename='dist/img/Logo.png') }}" height="70px"><b>P3I</b>
    </div>
    <h4>Contact Person: {{current_user.name}}</h4>
    <h3>Product</h3>
    <table border="1">
        <thead>
        <th>ID</th>
        <th>Name</th>
        <th>Location</th>
        <th>Quantity</th>
        <th>Received On</th>
        <th>Expiry</th>
        </thead>
        <tbody class="printdata">

        </tbody>
    </table>
</div>
<!-- print div -->
<b>
    <!-- /.content -->
</b>
{% endblock %}